### ISSUE TITLE
Cannot fetch by mix by default

### ISSUE THREAD

**Issue by liuyanghejerry** [ttvd/elixir-xxhash#1]
Hi, I can't install this module by default `mix deps.get`, which gives me result:

```
** (Mix) No package with name xxhash (from: mix.exs) in registry
```

Does this mean I have to install it by git?

**Comment by ttvd** [comment]
If you have a look at mix.exs , there are no deps. But if i run mix deps.get nothing happens. Not sure why you are getting that error.

**Comment by liuyanghejerry** [comment]
I think we have a little misunderstanding here. I mean when I write `xxhash` to `mix.exs` in my own project, `mix` cannot download this module and install it, which probably because `xxhash` is not properly registered on `hex.pm`.

Here I'm not talking about dependencies this module has. I know that this module depends on nothing.

How do you include this module in your other project?

**Comment by ttvd** [comment]
Ah yes! I have not done it; I manually specify local path dependency. I just did register it, hopefully this works.

https://hex.pm/packages/xxhash/0.2.0

Let me know if you find any issues. Thanks.

**Comment by ttvd** [comment]
Also please note, I implemented only 32 bit hashing (XX32). 64 bit hashing shouldn't be much harder to add (XX64).

**Comment by liuyanghejerry** [comment]
Thanks!
