### ISSUE TITLE
Issue new release of xxhash

### ISSUE THREAD

**Issue by derekkraan** [ttvd/elixir-xxhash#4]
Title says it all, I'd like to depend on a version of xxhash that works with elixir 1.7.

**Comment by ttvd** [comment]
Do you mind doing it? Pick a version. I won't be able to do that for a few days. I will merge your change.

**Comment by derekkraan** [comment]
Sure thing. By the way, I could merge this PR myself since you added me to your repository as a contributor. Just making sure that was intended.

I can't release the package myself though, for that you'd have to add me to hex.pm.

**Comment by ttvd** [comment]
Hi, thanks for the update. I did push the update to hex.pm. I could not figure out how to add you as collaborator there though. Please let me know if everything is working.
